Repository toy-land/backend, pull requests merged in 2021-02, with the labels that each got.

#5 Feat/drop-down-api
  src/main/java/com/openhack/toyland/controller/DropDownBoxContoller.java
  src/main/java/com/openhack/toyland/domain/BaseTimeEntity.java
  src/main/java/com/openhack/toyland/domain/Maintenance.java
  src/main/java/com/openhack/toyland/domain/MaintenanceRepository.java
  src/main/java/com/openhack/toyland/domain/Organization.java
  src/main/java/com/openhack/toyland/domain/OrganizationRepository.java
  src/main/java/com/openhack/toyland/domain/skill/Skill.java
  src/main/java/com/openhack/toyland/domain/skill/SkillRepository.java
  src/main/java/com/openhack/toyland/domain/skill/TechStack.java
  src/main/java/com/openhack/toyland/domain/skill/TechStackRepository.java
  src/main/java/com/openhack/toyland/domain/toy/Category.java
  src/main/java/com/openhack/toyland/domain/toy/Period.java
  src/main/java/com/openhack/toyland/domain/toy/Toy.java
  src/main/java/com/openhack/toyland/domain/toy/ToyRepository.java
  src/main/java/com/openhack/toyland/domain/user/Contributor.java
  src/main/java/com/openhack/toyland/domain/user/ContributorRepository.java
  src/main/java/com/openhack/toyland/domain/user/User.java
  src/main/java/com/openhack/toyland/domain/user/UserRepository.java
  src/main/java/com/openhack/toyland/dto/EnumDropDownResponse.java
  src/main/java/com/openhack/toyland/dto/OrganizationDropDownResponse.java
  src/main/java/com/openhack/toyland/dto/OrganizationResponse.java
  src/main/java/com/openhack/toyland/dto/SkillDropDownResponse.java
  src/main/java/com/openhack/toyland/dto/SkillResponse.java
  src/main/java/com/openhack/toyland/service/DropDownBoxService.java
  src/main/java/com/openhack/toyland/toy/Category.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/init.sql
Labels: enhancement

#6 Feat/toy crud
  src/main/java/com/openhack/toyland/controller/ToyController.java
  src/main/java/com/openhack/toyland/domain/Organization.java
  src/main/java/com/openhack/toyland/domain/toy/Category.java
  src/main/java/com/openhack/toyland/domain/toy/Toy.java
  src/main/java/com/openhack/toyland/domain/user/User.java
  src/main/java/com/openhack/toyland/dto/ContributorCreateRequest.java
  src/main/java/com/openhack/toyland/dto/ToyCreateRequest.java
  src/main/java/com/openhack/toyland/dto/ToyDetailResponse.java
  src/main/java/com/openhack/toyland/dto/ToyResponse.java
  src/main/java/com/openhack/toyland/exception/EntityNotFoundException.java
  src/main/java/com/openhack/toyland/service/toy/ToyCreateService.java
  src/main/java/com/openhack/toyland/service/toy/ToyService.java
  src/main/resources/application.yml
Labels: enhancement

#7 Feat/exception handling
  src/main/java/com/openhack/toyland/controller/advice/GlobalExceptionHandler.java
  src/main/java/com/openhack/toyland/dto/ErrorResponse.java
  src/main/java/com/openhack/toyland/exception/InvalidRequestBodyException.java
  src/main/java/com/openhack/toyland/exception/UnAuthorizedEventException.java
Labels: enhancement

#11 Feat/toy create complete
  src/main/java/com/openhack/toyland/controller/ToyController.java
  src/main/java/com/openhack/toyland/domain/skill/TechStack.java
  src/main/java/com/openhack/toyland/domain/user/Contributor.java
  src/main/java/com/openhack/toyland/domain/user/User.java
  src/main/java/com/openhack/toyland/domain/user/UserRepository.java
  src/main/java/com/openhack/toyland/dto/ToyCreateRequest.java
  src/main/java/com/openhack/toyland/service/toy/ToyCreateService.java
  src/test/java/com/openhack/toyland/domain/user/UserRepositoryTest.java
Labels: enhancement

#12 Feat/Infinite-scroll-pagination
  build.gradle
  src/main/java/com/openhack/toyland/controller/ToyController.java
  src/main/java/com/openhack/toyland/domain/toy/ToySearchAndSortRepository.java
  src/main/java/com/openhack/toyland/service/toy/ToyService.java
Labels: enhancement

#17 Feat/toy read and readme
  src/main/java/com/openhack/toyland/controller/ToyController.java
  src/main/java/com/openhack/toyland/domain/toy/Toy.java
  src/main/java/com/openhack/toyland/dto/ToyCreateRequest.java
  src/main/java/com/openhack/toyland/dto/ToyDetailResponse.java
  src/main/java/com/openhack/toyland/dto/ToyResponse.java
  src/main/java/com/openhack/toyland/dto/UserResponse.java
  src/main/java/com/openhack/toyland/service/toy/ToyService.java
Labels: enhancement

#19 Feat/create heatch check and active
  src/main/java/com/openhack/toyland/ToyLandApplication.java
  src/main/java/com/openhack/toyland/controller/advice/GlobalExceptionHandler.java
  src/main/java/com/openhack/toyland/domain/Maintenance.java
  src/main/java/com/openhack/toyland/domain/MaintenanceRepository.java
  src/main/java/com/openhack/toyland/domain/Organization.java
  src/main/java/com/openhack/toyland/domain/toy/ToyRepository.java
  src/main/java/com/openhack/toyland/domain/user/UserRepository.java
  src/main/java/com/openhack/toyland/dto/ToyCreateRequest.java
  src/main/java/com/openhack/toyland/exception/DuplicatedEntityException.java
  src/main/java/com/openhack/toyland/service/MaintenanceService.java
  src/main/java/com/openhack/toyland/service/toy/ToyCreateService.java
  src/test/java/com/openhack/toyland/domain/toy/ToyRepositoryTest.java
  src/test/java/com/openhack/toyland/domain/user/UserRepositoryTest.java
Labels: enhancement

#21 Bugfix/get toys api 수정
  build.gradle
  src/main/java/com/openhack/toyland/controller/ToyController.java
  src/main/java/com/openhack/toyland/domain/MaintenanceRepository.java
  src/main/java/com/openhack/toyland/domain/skill/TechStackRepository.java
  src/main/java/com/openhack/toyland/domain/toy/ToySearchAndSortRepository.java
  src/main/java/com/openhack/toyland/dto/ToyResponse.java
  src/main/java/com/openhack/toyland/service/toy/ToyService.java
Labels: bug-fix

#23 Feat/toy 삭제 및 수정 구현
  src/main/java/com/openhack/toyland/controller/ToyController.java
  src/main/java/com/openhack/toyland/domain/MaintenanceRepository.java
  src/main/java/com/openhack/toyland/domain/skill/TechStackRepository.java
  src/main/java/com/openhack/toyland/domain/toy/Toy.java
  src/main/java/com/openhack/toyland/domain/user/ContributorRepository.java
  src/main/java/com/openhack/toyland/dto/DeleteToyRequstBody.java
  src/main/java/com/openhack/toyland/dto/ErrorResponse.java
  src/main/java/com/openhack/toyland/dto/SimpleSuccessResponse.java
  src/main/java/com/openhack/toyland/dto/UpdateToyRequestBody.java
  src/main/java/com/openhack/toyland/exception/UnAuthorizedEventException.java
  src/main/java/com/openhack/toyland/service/toy/ToyService.java
  src/test/java/com/openhack/toyland/domain/toy/ToyRepositoryTest.java
Labels: enhancement

#24 Feat/create schedule
  build.gradle
  src/main/java/com/openhack/toyland/ToyLandApplication.java
  src/main/java/com/openhack/toyland/config/RestTemplateConfig.java
  src/main/java/com/openhack/toyland/domain/Maintenance.java
  src/main/java/com/openhack/toyland/exception/JsonParsingException.java
  src/main/java/com/openhack/toyland/infra/ApiParser.java
  src/main/java/com/openhack/toyland/service/maintenance/MaintenanceService.java
  src/main/java/com/openhack/toyland/service/maintenance/ScheduleService.java
  src/main/java/com/openhack/toyland/service/toy/ToyCreateService.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/application-prod.yml
  src/test/java/com/openhack/toyland/service/maintenance/MaintenanceServiceTest.java
Labels: enhancement

#28 feat: auto-complete api 구현
  src/main/java/com/openhack/toyland/controller/ToyController.java
  src/main/java/com/openhack/toyland/dto/SimpleToyResponse.java
  src/main/java/com/openhack/toyland/service/toy/ToyService.java
Labels: enhancement

#30 feat: sleepDays 구현
  src/main/java/com/openhack/toyland/domain/Maintenance.java
  src/main/java/com/openhack/toyland/service/maintenance/MaintenanceService.java
  src/main/java/com/openhack/toyland/service/maintenance/ScheduleService.java
Labels: enhancement

#31 Feat/mail server
  build.gradle
  src/main/java/com/openhack/toyland/domain/MaintenanceRepository.java
  src/main/java/com/openhack/toyland/domain/toy/ToyRepository.java
  src/main/java/com/openhack/toyland/dto/EmailParameters.java
  src/main/java/com/openhack/toyland/dto/EmailParticipant.java
  src/main/java/com/openhack/toyland/dto/EmailRequestBody.java
  src/main/java/com/openhack/toyland/infra/ApiParser.java
  src/main/java/com/openhack/toyland/infra/MailServer.java
  src/main/java/com/openhack/toyland/service/maintenance/MaintenanceService.java
  src/main/java/com/openhack/toyland/service/maintenance/ScheduleService.java
  src/main/java/com/openhack/toyland/service/toy/ToyService.java
  src/main/java/com/openhack/toyland/util/JsonTransformer.java
Labels: enhancement

#36 fix: delete method 에서는 body를 사용하지 않는다
  src/main/java/com/openhack/toyland/controller/ToyController.java
  src/main/java/com/openhack/toyland/service/toy/ToyService.java
Labels: bug-fix

#38 bugfix: sorting 추가
  src/main/java/com/openhack/toyland/dto/ToyResponse.java
  src/main/java/com/openhack/toyland/service/toy/ToyService.java
Labels: bug-fix

#39 Doc/readme
  README.md
Labels: documentation

#41 fix: update sleep days when toy service link is not empty string
  build.gradle
  src/main/java/com/openhack/toyland/ToyLandApplication.java
  src/main/java/com/openhack/toyland/config/ScheduledConfig.java
  src/main/java/com/openhack/toyland/domain/Maintenance.java
  src/main/java/com/openhack/toyland/domain/MaintenanceRepository.java
  src/main/java/com/openhack/toyland/domain/UpdatableMaintenance.java
  src/main/java/com/openhack/toyland/infra/ApiParser.java
  src/main/java/com/openhack/toyland/service/maintenance/MaintenanceService.java
  src/main/java/com/openhack/toyland/service/maintenance/ScheduleService.java
  src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
Labels: bug-fix

#44 email이 비어 있거나 null일 경우 healthcheck와 메일 보내기를 실행하지 않는다.
  src/main/java/com/openhack/toyland/domain/MaintenanceRepository.java
  src/main/java/com/openhack/toyland/domain/toy/Toy.java
  src/main/java/com/openhack/toyland/domain/toy/ToyRepository.java
  src/main/java/com/openhack/toyland/service/maintenance/ScheduleService.java
  src/main/java/com/openhack/toyland/service/toy/ToyService.java
  src/main/java/com/openhack/toyland/util/JsonTransformer.java
  src/test/java/com/openhack/toyland/domain/toy/ToyRepositoryTest.java
  src/test/java/com/openhack/toyland/service/maintenance/MaintenanceServiceTest.java
Labels: bug-fix

#45 Test/testcontainer config
  build.gradle
  src/test/java/com/openhack/toyland/IntegrationTest.java
  src/test/java/com/openhack/toyland/domain/user/UserRepositoryTest.java
  src/test/java/com/openhack/toyland/service/maintenance/MaintenanceServiceTest.java
  src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
  src/test/resources/application-test.yml
  src/test/resources/db/init-test.sql
  src/test/resources/db/insert-test.sql
  src/test/resources/db/truncate-test.sql
Labels: test

#47 Maintenenance의 created_date가 안들어가는 이유를 파악한다
  src/main/java/com/openhack/toyland/dto/ContributorCreateRequest.java
  src/main/java/com/openhack/toyland/dto/ToyCreateRequest.java
  src/test/java/com/openhack/toyland/IntegrationTest.java
  src/test/java/com/openhack/toyland/PersistenceTest.java
  src/test/java/com/openhack/toyland/controller/ToyControllerTest.java
  src/test/java/com/openhack/toyland/service/maintenance/MaintenanceServiceTest.java
  src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
Labels: bug-fix

#49 Refactor: ToyDetailResponse 에서 하드코딩 된 영역을 수정한다
  src/main/java/com/openhack/toyland/controller/DropDownBoxContoller.java
  src/main/java/com/openhack/toyland/controller/ToyController.java
  src/main/java/com/openhack/toyland/controller/advice/GlobalExceptionHandler.java
  src/main/java/com/openhack/toyland/domain/Maintenance.java
  src/main/java/com/openhack/toyland/domain/MaintenanceRepository.java
  src/main/java/com/openhack/toyland/domain/Organization.java
  src/main/java/com/openhack/toyland/domain/UpdatableMaintenance.java
  src/main/java/com/openhack/toyland/domain/skill/TechStackRepository.java
  src/main/java/com/openhack/toyland/domain/toy/Period.java
  src/main/java/com/openhack/toyland/domain/toy/ToyRepository.java
  src/main/java/com/openhack/toyland/dto/ContributorCreateRequest.java
  src/main/java/com/openhack/toyland/dto/DeleteToyRequstBody.java
  src/main/java/com/openhack/toyland/dto/EmailParticipant.java
  src/main/java/com/openhack/toyland/dto/EmailRequestBody.java
  src/main/java/com/openhack/toyland/dto/EnumDropDownResponse.java
  src/main/java/com/openhack/toyland/dto/ErrorResponse.java
  src/main/java/com/openhack/toyland/dto/OrganizationDropDownResponse.java
  src/main/java/com/openhack/toyland/dto/OrganizationResponse.java
  src/main/java/com/openhack/toyland/dto/SkillDropDownResponse.java
  src/main/java/com/openhack/toyland/dto/SkillResponse.java
  src/main/java/com/openhack/toyland/dto/ToyCreateRequest.java
  src/main/java/com/openhack/toyland/dto/ToyDetailResponse.java
  src/main/java/com/openhack/toyland/dto/UpdateToyRequestBody.java
  src/main/java/com/openhack/toyland/exception/DuplicatedEntityException.java
  src/main/java/com/openhack/toyland/exception/InvalidRequestBodyException.java
  src/main/java/com/openhack/toyland/exception/UnAuthorizedEventException.java
  src/main/java/com/openhack/toyland/infra/ApiParser.java
  src/main/java/com/openhack/toyland/infra/MailServer.java
  src/main/java/com/openhack/toyland/service/DropDownBoxService.java
  src/main/java/com/openhack/toyland/service/maintenance/MaintenanceService.java
  src/main/java/com/openhack/toyland/service/maintenance/ScheduleService.java
  src/main/java/com/openhack/toyland/service/toy/ToyCreateService.java
  src/main/java/com/openhack/toyland/service/toy/ToyService.java
  src/test/java/com/openhack/toyland/PersistenceTest.java
  src/test/java/com/openhack/toyland/controller/DropDownBoxControllerTest.java
  src/test/java/com/openhack/toyland/controller/ToyControllerTest.java
  src/test/java/com/openhack/toyland/service/maintenance/MaintenanceServiceTest.java
  src/test/java/com/openhack/toyland/service/maintenance/ScheduleServiceTest.java
  src/test/java/com/openhack/toyland/service/toy/ToyDeleteServiceTest.java
  src/test/java/com/openhack/toyland/service/toy/ToyFindSingleServiceTest.java
  src/test/java/com/openhack/toyland/service/toy/ToyUpdateServiceTest.java
  src/test/resources/db/init-test.sql
  src/test/resources/db/insert-test.sql
Labels: bug-fix, test
